version: '3'

services:
  mobiage-db:
    image: postgres:11.16-alpine
    container_name: hospitalapp-db
    restart: always
    ports:
      - "9060:5432"
    environment:
      POSTGRES_USER: "hospitalapp"
      POSTGRES_DB: "hospitalapp"
      POSTGRES_PASSWORD: "123456"

